# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Bhargesh Patel
title: 
email: pbhargesh82@gmail.com
website: https://pbhargesh82.github.io/pbhargesh82-github.io/

# Social links
twitter_username: pbhargesh82
github_username:  pbhargesh82
# dribbble_username: jekyll
facebook_username: pbhargesh82
# flickr_username: jekyll
instagram_username: pbhargesh82
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
googleplus_username: pbhargesh82

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Bhargesh and I'm looking to establish myself  as  a technocrat  in  the technological area, utilizing my  skills  for the benefit of  the corporate and the society as  whole.


  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
