# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Bhargesh Patel
#title: Fresher
email: pbhargesh82@gmail.com
phone: 9033719592
#website: https://pbhargesh82.github.io/pbhargesh82-github.io/

# Social links
twitter_username: pbhargesh82
github_username:  pbhargesh82
# dribbble_username: jekyll
facebook_username: bhargesh.patel.549
# flickr_username: jekyll
instagram_username: pbhargesh82
linkedin_username: bhargesh-patel-2b6a111b9
# pinterest_username: jekyll
#youtube_username: globalmtb
#googleplus_username: pbhargesh82

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Bhargesh Patel and I'm looking to establish myself as a technocrat in the technological area, utilizing my skills for the benefit of the corporate and the society as whole.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Skills Section
# skills_title: Skills

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Music
   - Gaming
   - Strategic Games
   

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
